package com.weilai.jigsawpuzzle;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.weilai.jigsawpuzzle.db.RecordInfo;

import com.weilai.jigsawpuzzle.RecordInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recordInfoDaoConfig;

    private final RecordInfoDao recordInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recordInfoDaoConfig = daoConfigMap.get(RecordInfoDao.class).clone();
        recordInfoDaoConfig.initIdentityScope(type);

        recordInfoDao = new RecordInfoDao(recordInfoDaoConfig, this);

        registerDao(RecordInfo.class, recordInfoDao);
    }
    
    public void clear() {
        recordInfoDaoConfig.clearIdentityScope();
    }

    public RecordInfoDao getRecordInfoDao() {
        return recordInfoDao;
    }

}
